changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - bugfix
    - title: "🔒 Security"
      labels:
        - security
    - title: "📚 Documentation"
      labels:
        - documentation
        - docs
    - title: "🧰 Maintenance"
      labels:
        - chore
        - maintenance
    - title: "📦 Dependencies"
      labels:
        - dependencies

