// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/palisadeinc/wallet-recovery-cli/utils (interfaces: TSMClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_tsm_client.go -package=mocks github.com/palisadeinc/wallet-recovery-cli/utils TSMClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	rsa "crypto/rsa"
	reflect "reflect"

	tsm "gitlab.com/Blockdaemon/go-tsm-sdkv2/v70/tsm"
	gomock "go.uber.org/mock/gomock"
)

// MockTSMClient is a mock of TSMClient interface.
type MockTSMClient struct {
	ctrl     *gomock.Controller
	recorder *MockTSMClientMockRecorder
	isgomock struct{}
}

// MockTSMClientMockRecorder is the mock recorder for MockTSMClient.
type MockTSMClientMockRecorder struct {
	mock *MockTSMClient
}

// NewMockTSMClient creates a new mock instance.
func NewMockTSMClient(ctrl *gomock.Controller) *MockTSMClient {
	mock := &MockTSMClient{ctrl: ctrl}
	mock.recorder = &MockTSMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTSMClient) EXPECT() *MockTSMClientMockRecorder {
	return m.recorder
}

// ECDSADerivePrivateKey mocks base method.
func (m *MockTSMClient) ECDSADerivePrivateKey(masterKey, chainCode []byte, path []uint32) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ECDSADerivePrivateKey", masterKey, chainCode, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ECDSADerivePrivateKey indicates an expected call of ECDSADerivePrivateKey.
func (mr *MockTSMClientMockRecorder) ECDSADerivePrivateKey(masterKey, chainCode, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ECDSADerivePrivateKey", reflect.TypeOf((*MockTSMClient)(nil).ECDSADerivePrivateKey), masterKey, chainCode, path)
}

// ECDSARecoverPrivateKey mocks base method.
func (m *MockTSMClient) ECDSARecoverPrivateKey(recoveryData []byte, ersPrivateKey *rsa.PrivateKey, label []byte) (*tsm.ECDSARecoveredPrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ECDSARecoverPrivateKey", recoveryData, ersPrivateKey, label)
	ret0, _ := ret[0].(*tsm.ECDSARecoveredPrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ECDSARecoverPrivateKey indicates an expected call of ECDSARecoverPrivateKey.
func (mr *MockTSMClientMockRecorder) ECDSARecoverPrivateKey(recoveryData, ersPrivateKey, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ECDSARecoverPrivateKey", reflect.TypeOf((*MockTSMClient)(nil).ECDSARecoverPrivateKey), recoveryData, ersPrivateKey, label)
}

// ECDSAValidateRecoveryData mocks base method.
func (m *MockTSMClient) ECDSAValidateRecoveryData(recoveryData, publicKey []byte, ersPublicKey *rsa.PublicKey, label []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ECDSAValidateRecoveryData", recoveryData, publicKey, ersPublicKey, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// ECDSAValidateRecoveryData indicates an expected call of ECDSAValidateRecoveryData.
func (mr *MockTSMClientMockRecorder) ECDSAValidateRecoveryData(recoveryData, publicKey, ersPublicKey, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ECDSAValidateRecoveryData", reflect.TypeOf((*MockTSMClient)(nil).ECDSAValidateRecoveryData), recoveryData, publicKey, ersPublicKey, label)
}

// SchnorrRecoverPrivateKey mocks base method.
func (m *MockTSMClient) SchnorrRecoverPrivateKey(recoveryData []byte, ersPrivateKey *rsa.PrivateKey, label []byte) (*tsm.SchnorrRecoveredPrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchnorrRecoverPrivateKey", recoveryData, ersPrivateKey, label)
	ret0, _ := ret[0].(*tsm.SchnorrRecoveredPrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SchnorrRecoverPrivateKey indicates an expected call of SchnorrRecoverPrivateKey.
func (mr *MockTSMClientMockRecorder) SchnorrRecoverPrivateKey(recoveryData, ersPrivateKey, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchnorrRecoverPrivateKey", reflect.TypeOf((*MockTSMClient)(nil).SchnorrRecoverPrivateKey), recoveryData, ersPrivateKey, label)
}

// SchnorrValidateRecoveryData mocks base method.
func (m *MockTSMClient) SchnorrValidateRecoveryData(recoveryData, publicKey []byte, ersPublicKey *rsa.PublicKey, label []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchnorrValidateRecoveryData", recoveryData, publicKey, ersPublicKey, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// SchnorrValidateRecoveryData indicates an expected call of SchnorrValidateRecoveryData.
func (mr *MockTSMClientMockRecorder) SchnorrValidateRecoveryData(recoveryData, publicKey, ersPublicKey, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchnorrValidateRecoveryData", reflect.TypeOf((*MockTSMClient)(nil).SchnorrValidateRecoveryData), recoveryData, publicKey, ersPublicKey, label)
}
