package ers

import (
	"crypto/ecdsa"
	"fmt"

	"github.com/palisadeinc/mpc-recovery/math"
)

type Decryptor interface {
	Decrypt(ciphertext, label []byte) (plaintext []byte, err error)
}

// RecoverPrivateKey recovers private key and chain code from the recovery data.
// The decryptor must be able to decrypt ciphertext encrypted under the ERS public key using RSA-OAEP with SHA-256 with
// the given label. The output consists of the name of the elliptic curve, the private key in big endian byte format
// and the chain code.
// If chainPath is nil, the master private key and master chain code will be returned, otherwise it is the derived
// private key and derived chain code according to the given chain path.
// NOTE: If called with DKLS18 or SEPH18S recovery data generated by TSM version 43.2.0
// or earlier, RecoverPrivateKey() will return the master chain code seed and not the master chain code.
// The same holds if called with EdDSA recovery data generated before TSM 43.0.0 and DKLS19 recovery data
// generated before TSM 28.0.0. It is easy to obtain the master chain code from the master chain code as follows:
//
//	d := HMAC(SHA-512, key="Bitcoin seed", data=[master chaincode seed])
//	master chain code := d[0:32]
//
// Recovery data generated with more recent versions of the TSM will return the master chain code for all protocols.
func RecoverPrivateKey(decryptor Decryptor, label, recoveryData []byte, chainPath []uint32) (ellipticCurve string, derivedPrivateKey []byte, derivedChainCode []byte, err error) {

	version, err := getVersion(recoveryData)
	if err != nil {
		return "", nil, nil, err
	}

	var privateMasterKeyBytes, masterChainCode []byte
	switch version {
	case RecoveryDataVersion1:
		ellipticCurve, privateMasterKeyBytes, masterChainCode, err = recoverPrivateKeyV1(decryptor, label, recoveryData)
	case RecoveryDataVersion2:
		ellipticCurve, privateMasterKeyBytes, masterChainCode, err = recoverPrivateKeyV2(decryptor, label, recoveryData)
	case RecoveryDataVersion3:
		ellipticCurve, privateMasterKeyBytes, masterChainCode, err = recoverPrivateKeyV3(decryptor, label, recoveryData)
	default:
		return "", nil, nil, fmt.Errorf("unsupported recovery data version: %s", version)
	}

	if err != nil {
		return "", nil, nil, err
	}

	curve, err := math.NewCurve(ellipticCurve)
	if err != nil {
		return "", nil, nil, err
	}

	var derivedPrivKey math.Scalar

	privateMasterKey := curve.NewScalarBytes(privateMasterKeyBytes)
	publicMasterKey := curve.G().Mul(privateMasterKey)

	if chainPath == nil {
		return ellipticCurve, privateMasterKeyBytes, masterChainCode, nil
	}

	switch curve.Name() {
	case "secp256k1":
		_, derivedPrivKey, derivedChainCode, err = DeriveSecp256k1(publicMasterKey, privateMasterKey, masterChainCode, chainPath)
	case "ED-25519":
		_, derivedPrivKey, derivedChainCode, err = DeriveEd25519(publicMasterKey, privateMasterKey, masterChainCode, chainPath)
	case "P-224", "P-256", "P-384", "P-521":
		return "", nil, nil, fmt.Errorf("key derivation not supported for curve: %s", ellipticCurve)
	default:
		return "", nil, nil, fmt.Errorf("unsupported curve: %s", ellipticCurve)
	}

	return ellipticCurve, derivedPrivKey.Encode(), derivedChainCode, err

}

// PrivateKeyToECDSAPrivateKey takes the name of an elliptic curve and a private key as output by RecoverPrivateKey and
// returns an ecdsa.PrivateKey. If the elliptic curve does not support ECDSA an error is returned.
func PrivateKeyToECDSAPrivateKey(ellipticCurve string, privateKey []byte) (ecdsaPrivateKey *ecdsa.PrivateKey, err error) {
	curve, err := math.NewCurve(ellipticCurve)
	if err != nil {
		return nil, err
	}

	if err = curveSupportsECDSA(curve); err != nil {
		return nil, err
	}

	scalarPrivateKey := curve.NewScalarBytes(privateKey)
	publicKeyX, publicKeyY := curve.G().Mul(scalarPrivateKey).Coordinates()

	ecdsaPrivateKey = &ecdsa.PrivateKey{
		PublicKey: ecdsa.PublicKey{
			Curve: curve.Impl(),
			X:     publicKeyX,
			Y:     publicKeyY,
		},
		D: scalarPrivateKey.Value(),
	}

	return ecdsaPrivateKey, nil
}

// PrivateKeyToASN1PrivateKey takes the name of an elliptic curve and a private key as output by RecoverPrivateKey and
// returns an ECDSA private key in SEC 1, ASN.1 DER format.
func PrivateKeyToASN1PrivateKey(ellipticCurve string, privateKey []byte) (asn1PrivateKey []byte, err error) {
	curve, err := math.NewCurve(ellipticCurve)
	if err != nil {
		return nil, err
	}

	if err = curveSupportsECDSA(curve); err != nil {
		return nil, err
	}

	ecdsaPrivateKey, err := PrivateKeyToECDSAPrivateKey(ellipticCurve, privateKey)
	if err != nil {
		return nil, err
	}

	asn1PrivateKey, err = marshalECPrivateKey(ecdsaPrivateKey)
	if err != nil {
		return nil, fmt.Errorf("error marshalling private key: %s", err)
	}

	return asn1PrivateKey, nil
}

func curveSupportsECDSA(curve math.Curve) error {
	switch curve.Impl().Params().Name {
	case "P-224", "P-256", "P-384", "P-521", "secp256k1":
		return nil
	default:
		return fmt.Errorf("elliptic curve does not support ECDSA: %s", curve.Impl().Params().Name)
	}
}
